/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'authorId' : UserId,
  'createdAt' : Time,
  'text' : string,
  'postId' : PostId,
}
export type ExternalBlob = Uint8Array;
export type MediaType = { 'video' : null } |
  { 'photo' : null };
export interface Message {
  'id' : MessageId,
  'createdAt' : Time,
  'text' : string,
  'receiverId' : UserId,
  'senderId' : UserId,
}
export type MessageId = bigint;
export interface Notification {
  'id' : NotificationId,
  'createdAt' : Time,
  'read' : boolean,
  'type' : NotificationType,
  'actorId' : UserId,
  'recipientId' : UserId,
  'postId' : [] | [PostId],
}
export type NotificationId = bigint;
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'follow' : null };
export interface Post {
  'id' : PostId,
  'media' : ExternalBlob,
  'authorId' : UserId,
  'createdAt' : Time,
  'caption' : string,
  'mediaType' : MediaType,
}
export type PostId = bigint;
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'profilePhoto' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createComment' : ActorMethod<[PostId, string], Comment>,
  'createPost' : ActorMethod<[ExternalBlob, MediaType, string], Post>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[UserId], Array<Message>>,
  'getExploreFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getHomeFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPostComments' : ActorMethod<[PostId], Array<Comment>>,
  'getPostLikes' : ActorMethod<[PostId], Array<UserId>>,
  'getRecentConversations' : ActorMethod<[], Array<UserId>>,
  'getUserPosts' : ActorMethod<[UserId], Array<Post>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationsAsRead' : ActorMethod<[Array<NotificationId>], undefined>,
  'registerUser' : ActorMethod<[string, string], UserProfile>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[UserId, string], Message>,
  'toggleLike' : ActorMethod<[PostId], boolean>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    UserProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];