/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostId = IDL.Nat;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'authorId' : UserId,
  'createdAt' : Time,
  'text' : IDL.Text,
  'postId' : PostId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : PostId,
  'media' : ExternalBlob,
  'authorId' : UserId,
  'createdAt' : Time,
  'caption' : IDL.Text,
  'mediaType' : MediaType,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'createdAt' : Time,
  'text' : IDL.Text,
  'receiverId' : UserId,
  'senderId' : UserId,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'createdAt' : Time,
  'read' : IDL.Bool,
  'type' : NotificationType,
  'actorId' : UserId,
  'recipientId' : UserId,
  'postId' : IDL.Opt(PostId),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
  'createPost' : IDL.Func([ExternalBlob, MediaType, IDL.Text], [Post], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getExploreFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getHomeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPostComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getPostLikes' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
  'getRecentConversations' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getUserPosts' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationsAsRead' : IDL.Func([IDL.Vec(NotificationId)], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [Message], []),
  'toggleLike' : IDL.Func([PostId], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostId = IDL.Nat;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'authorId' : UserId,
    'createdAt' : Time,
    'text' : IDL.Text,
    'postId' : PostId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const Post = IDL.Record({
    'id' : PostId,
    'media' : ExternalBlob,
    'authorId' : UserId,
    'createdAt' : Time,
    'caption' : IDL.Text,
    'mediaType' : MediaType,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'createdAt' : Time,
    'text' : IDL.Text,
    'receiverId' : UserId,
    'senderId' : UserId,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'type' : NotificationType,
    'actorId' : UserId,
    'recipientId' : UserId,
    'postId' : IDL.Opt(PostId),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
    'createPost' : IDL.Func([ExternalBlob, MediaType, IDL.Text], [Post], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getExploreFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getHomeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPostComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getPostLikes' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
    'getRecentConversations' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getUserPosts' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationsAsRead' : IDL.Func([IDL.Vec(NotificationId)], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [Message], []),
    'toggleLike' : IDL.Func([PostId], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };